name: Deploy Payment Frontend Dev

on:
  push:
    branches:
      - paymentfrontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kod
        uses: actions/checkout@v4

      - name: Logga in på Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Bygg och pusha Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/webshop-frontend-group-2:payment-dev
